### ISSUE TITLE
After installed the plugins zip, AS 3.5.3 stuck at splash screen

### ISSUE THREAD

**Issue by Maxwell6635** [MPArnold/android-drawable-importer-intellij-plugin#2]
Hi after I tried to install the plugins zip, its caused AS stuck at splash screen.

I am using Mac OS Catalina 10.15.2 (19C57).

**Comment by MPArnold** [comment]
OK - I have only tested on Linux. What do you mean by 'splash' screen - are you saying Android Studio does not initialize? Any info from 'idea.log' or from the bottom right warning button that is visible after some fatal exception?

Installation of the hack does not overwrite the original. Have you definitely deleted the old plugin?

**Comment by Maxwell6635** [comment]
What do you mean by 'splash' screen - are you saying Android Studio does not initialize?  
Here are the screen I referring, its always stuck on this screen.
<img width="472" alt="Screenshot 2020-01-31 at 1 54 46 PM" src="https://user-images.githubusercontent.com/12591474/73515760-6235ca00-4431-11ea-862d-c8fb2cc65aa4.png">

Any info from 'idea.log' or from the bottom right warning button that is visible after some fatal exception?
Unfortunately, I unable provide any log as I unable get into load project.

Installation of the hack does not overwrite the original. Have you definitely deleted the old plugin?
Yup, I uninstall the old plugins, and install the hack version. But I think it's doesn't solve originally issues created by old plugins.

**Comment by MPArnold** [comment]
Interesting. This is different to the problem Linux users were experiencing after installing AS3.5.
Next step: Find and clear 'idea.log'. Re-run and post the log. 
One other point: First time install does a lot of 1-time only processing that I suppose could be very slow on some systems. Maybe allow more time before cancelling?

**Comment by Maxwell6635** [comment]
Interesting, after I clear the Log and some caches in AS Folder. It's working fine now. Thanks for your helps.

[idea.log](https://github.com/MPArnold/android-drawable-importer-intellij-plugin/files/4137920/idea.log)
Here are the log where it's stuck at splash screen.

**Comment by MPArnold** [comment]
That's great news - but I'm still worried that you found a bug.

When you have time, could you please tell me what files you see in the following folder:
**/Users/......./Library/Caches/AndroidStudio3.5/ADI-hack-export**

Much appreciated.

**Comment by Maxwell6635** [comment]
haha, alright. Here you goes. 
<img width="1159" alt="Screenshot 2020-01-31 at 5 21 23 PM" src="https://user-images.githubusercontent.com/12591474/73531261-01b88400-4455-11ea-87d3-22cb5dd7cac2.png">

**Comment by MPArnold** [comment]
Contents of this folder are as expected.

The absence of **ADI-hack-export** folder, or a difference in the version number of the contained **.properties** file will fire the 1-time install processing.  This folder can safely be deleted at any time.

The actual location of this folder is determined by PathManager.getSystemPath() which returns a result dictated by the local configuration.

In your case, deleting the cache also deleted this folder.

The original installation log shows that this folder was created successfully but that the installation task froze before it could be populated. No evidence of a loop.

So it's still a bit of a mystery!!!
