### ISSUE TITLE
Plugin not running & not shown at Android Studio Arctic Fox | Built on July 27, 2021

### ISSUE THREAD

**Issue by mrrezkii** [MPArnold/android-drawable-importer-intellij-plugin#3]
![Screenshot](https://user-images.githubusercontent.com/26183939/127941472-eb735143-b134-4a5a-9d77-67a5490ea8b8.png)

**Comment by qjirapong** [comment]
Looks like there is a fix now.

https://stackoverflow.com/a/68739316
